create schema if not exists holidaycalendar;

create table if not exists holidaycalendar.people_allowance (
  id bigint generated by default as identity primary key,
  name text not null,
  standard_days numeric not null default 28,
  additional_days numeric not null default 0,
  created_at timestamptz not null default now(),
  allowance_year integer not null
);

create unique index if not exists people_allowance_name_year_key
on holidaycalendar.people_allowance(name, allowance_year);

create table if not exists holidaycalendar.holidays (
  id bigint generated by default as identity primary key,
  location text not null,
  country text,
  start_date date not null,
  start_half text not null default 'am',
  end_date date not null,
  end_half text not null default 'pm',
  days numeric not null,
  days_off_work numeric,
  status text not null default 'ideation',
  people_days jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  constraint holidays_status_check check (status in ('ideation','planning','booked','happened')),
  constraint holidays_start_half_check check (start_half in ('am', 'pm')),
  constraint holidays_end_half_check check (end_half in ('am', 'pm'))
);

create table if not exists holidaycalendar.bank_holidays (
  id bigint generated by default as identity primary key,
  holiday_year integer not null,
  holiday_date date not null,
  name text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists bank_holidays_year_date_key
on holidaycalendar.bank_holidays(holiday_year, holiday_date);

create table if not exists holidaycalendar.people (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamptz not null default now()
);

alter table holidaycalendar.people_allowance enable row level security;
alter table holidaycalendar.holidays enable row level security;
alter table holidaycalendar.bank_holidays enable row level security;
alter table holidaycalendar.people enable row level security;

drop policy if exists "allow all people" on holidaycalendar.people_allowance;
create policy "allow all people" on holidaycalendar.people_allowance
for all
using (true)
with check (true);

drop policy if exists "allow all holidays" on holidaycalendar.holidays;
create policy "allow all holidays" on holidaycalendar.holidays
for all
using (true)
with check (true);

drop policy if exists "allow all bank holidays" on holidaycalendar.bank_holidays;
create policy "allow all bank holidays" on holidaycalendar.bank_holidays
for all
using (true)
with check (true);

drop policy if exists "allow all people table" on holidaycalendar.people;
create policy "allow all people table" on holidaycalendar.people
for all
using (true)
with check (true);
