create table if not exists public.people_allowance (
  id bigint generated by default as identity primary key,
  name text unique not null,
  standard_days numeric not null default 28,
  additional_days numeric not null default 0,
  created_at timestamptz not null default now()
);

create table if not exists public.holidays (
  id bigint generated by default as identity primary key,
  location text not null,
  start_date date not null,
  end_date date not null,
  days numeric not null,
  people_days jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.people_allowance enable row level security;
alter table public.holidays enable row level security;

drop policy if exists "allow all people" on public.people_allowance;
create policy "allow all people" on public.people_allowance
for all
using (true)
with check (true);

drop policy if exists "allow all holidays" on public.holidays;
create policy "allow all holidays" on public.holidays
for all
using (true)
with check (true);
