create table if not exists public.bank_holidays (
  id bigint generated by default as identity primary key,
  holiday_year integer not null,
  holiday_date date not null,
  name text not null,
  created_at timestamptz not null default now()
);

create unique index if not exists bank_holidays_year_date_key
on public.bank_holidays(holiday_year, holiday_date);

alter table public.bank_holidays enable row level security;

drop policy if exists "allow all bank holidays" on public.bank_holidays;
create policy "allow all bank holidays" on public.bank_holidays
for all
using (true)
with check (true);
