create table if not exists public.people (
  id bigint generated by default as identity primary key,
  name text unique not null,
  created_at timestamptz not null default now()
);

insert into public.people(name)
select distinct pa.name
from public.people_allowance pa
where pa.name is not null
on conflict (name) do nothing;

alter table public.people enable row level security;

drop policy if exists "allow all people table" on public.people;
create policy "allow all people table" on public.people
for all
using (true)
with check (true);
